# --- QMIX specific parameters ---

# use epsilon greedy action selector
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 50000

runner: "episode"

buffer_size: 5000

# update the target network every {} episodes
target_update_interval: 200

# use the Q_Learner to train
agent_output_type: "q"
learner: "mgan_learner"
double_q: True
mixer: "mgan_mix"
name: "mgan_mix"

add_self: False
concat: True
sample_num: null
hidden_dim: 32
hyper_hidden_dim: 64
head_num: 4

aggregator_args:
  method: "atten"
